select * from customer_behaviour
limit 10;

--  1Revenue by Gender – Compared total revenue generated by male vs. female customers.
select gender,sum(purchase_amount) as revenue from customer_behaviour
group by gender;

 --2 High-Spending Discount Users – Identified customers who used discounts but still 
--spent above the average purchase amount .

select customer_id , purchase_amount from customer_behaviour 
where discount_applied ='Yes' and  purchase_amount>= (select avg(purchase_amount) from customer_behaviour);


--3 Top 5 Products by Rating – Found products with the highest average review ratings.

select item_purchased as products, ROUND(avg(review_rating::numeric),3 )as rating  from customer_behaviour

group by item_purchased 
order by avg(review_rating) desc  
limit 5;

--4Shipping Type Comparison – Compared average purchase amounts between Standard and Express shipping.

select shipping_type,round(avg(purchase_amount::numeric),2) as purchase from customer_behaviour
where  shipping_type in ('Standard','Express')
group by shipping_type;

--
select * from customer_behaviour
limit 10;

-- 5 Subscribers vs. Non-Subscribers – Compared average spend and total revenue across subscription status.

select subscription_status, count(customer_id) as Total_customer, round(avg(purchase_amount::numeric),2) as avg_amount,
sum(purchase_amount) as total_revenu
from customer_behaviour 
--where subscription_status in ('Yes','No')
group by subscription_status ;

-- 6 Discount-Dependent Products – Identified 5 products with the highest percentage of discounted purchases.

select item_purchased as product,  
round(sum(case when discount_applied='Yes' then 1     else 0 ) / count(*)*100,2) as discount_rate
from customer_behaviour
group by item_purchased 
order by discount_rate desc 
limit 5;




-- 7Customer Segmentation – Classified customers into New, Returning, and Loyal   segments based on purchase history.

with customer_type as (
     select customer_id,previous_purchases,
	 case 
	 when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'returning'
	 else 'loyal'
	 end as customer_segment
	 from customer_behaviour)

	 select customer_segment , count(*) as No_customer from customer_type
	 group by customer_segment 

	 

-- 8 Top 3 Products per Category – Listed the most purchased products within each  category

with items as (

select category as product_category , item_purchased,count(customer_id) as total_order ,
      row_number () over(partition by category order by count(customer_id) desc) as item_rank
	  
      from customer_behaviour
	  
	  group by category , item_purchased
	  )
	  select item_rank ,product_category ,item_purchased,total_order
	  from items
	  where item_rank<=3;
	  


-- 9 Repeat Buyers & Subscriptions – Checked whether customers with >5 purchases are more likely to subscribe.

select subscription_status , count(*) as repet_buyeers
from customer_behaviour
where previous_purchases >5
group by subscription_status 

select * from customer_behaviour
limit 10 ;
--10 Revenue by Age Group – Calculated total revenue contribution of each age group.

select  age_group , sum(purchase_amount) as total_revenu
from customer_behaviour
group by age_group 
order by total_revenu desc;









